import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    title: "AIR MORE UPTEMPO '96 'DARK SMOKE GREY'",
    brand: "Sneakers",
    priceInMrp: 9999,
    discountInPercentage: 50,
    categoryName: "Reebok",
    inStock: 4,
    featured: true,
    starRating: 4.0,
    cashOnDelivery: true,
    fastDelivery: false,
    imageSrc:
      "https://www.superkicks.in/products/classic-leather-hemp?_pos=10&_fid=2afa1d937&_ss=c&variant=45134045217019",
  },
  {
    _id: uuid(),
    title: "AIR MAX 90 GORE-TEX 'DK SMOKE GREY/SUMMIT WHITE-COOL GREY'",
    brand: "Skateboarding Sneakers",
    priceInMrp: 6990,
    discountInPercentage: 64,
    categoryName: "Nike",
    inStock: 12,
    featured: true,
    starRating: 4.6,
    cashOnDelivery: true,
    fastDelivery: true,
    imageSrc:
      "https://www.superkicks.in/products/air-max-90-neutral-olive-black-medium-olive?_pos=10&_fid=ce29164cc&_ss=c&variant=45238566813947",
  },
  {
    _id: uuid(),
    title: "Smart Band M3",
    brand: "Classic Sneakers",
    priceInMrp: 3999,
    discountInPercentage: 70,
    categoryName: "Puma",
    inStock: 20,
    featured: true,
    starRating: 3.8,
    cashOnDelivery: true,
    fastDelivery: false,
    imageSrc:
      "https://www.superkicks.in/products/blktop-rider-washed-astro-red-team-regel-red?_pos=12&_fid=e2a2dc3be&_ss=c",
  },
  {
    _id: uuid(),
    title: "AIR MAX 90 'NEUTRAL OLIVE/BLACK-MEDIUM OLIVE'",
    brand: "Basketball Sneakers",
    priceInMrp: 44499,
    discountInPercentage: 27,
    categoryName: "Adidas",
    inStock: 0,
    featured: true,
    starRating: 4.8,
    cashOnDelivery: false,
    fastDelivery: false,
    imageSrc: "https://www.superkicks.in/cdn/shop/files/4-2024-03-01T190401.569.jpg?v=1709300091&width=600",
  },
  {
    _id: uuid(),
    title: "Nike Adapt BB",
    brand: "Basketball Sneakers",
    priceInMrp: 36990,
    discountInPercentage: 40,
    categoryName: "Adidas",
    inStock: 2,
    featured: true,
    starRating: 4.1,
    cashOnDelivery: false,
    fastDelivery: true,
    imageSrc:
      "https://www.superkicks.in/products/dame-8-extply-better-scarlet-cloud-white?_pos=1&_fid=24b21ed12&_ss=c",
  },
  {
    _id: uuid(),
    title: "DUNK HIGH RETRO SE 'GRAIN/BLACK-LIGHT PUMICE-PALE VANILLA'",
    brand: "Classic Sneakers",
    priceInMrp: 5999,
    discountInPercentage: 67,
    categoryName: "Nike",
    inStock: 16,
    featured: false,
    starRating: 4.1,
    cashOnDelivery: true,
    fastDelivery: true,
    imageSrc: "https://www.superkicks.in/products/air-force-1-07-white-photo-blue-white?_pos=3&_fid=e3aac2386&_ss=c&variant=45165833748731",
  },
  {
    _id: uuid(),
    title: "DUNK HIGH RETRO SE 'GRAIN/BLACK-LIGHT PUMICE-PALE VANILLA'",
    brand: "Slides",
    priceInMrp: 6990,
    discountInPercentage: 64,
    categoryName: "Nike",
    inStock: 6,
    featured: true,
    starRating: 4.4,
    cashOnDelivery: true,
    fastDelivery: true,
    imageSrc: "https://cdn.shopify.com/s/files/1/0659/0722/8923/files/2_5879bb77-23aa-4679-ad59-fc3ed75eeb2b.jpg?v=1708934707&width=360",
  },
  {
    _id: uuid(),
    title: "CLASSIC LEATHER 'RED/CARBON BLACK/CLOUD WHITE",
    brand: "Slides",
    priceInMrp: 2799,
    discountInPercentage: 39,
    categoryName: "Reebok",
    inStock: 18,
    featured: true,
    starRating: 3.9,
    cashOnDelivery: true,
    fastDelivery: true,
    imageSrc: "https://cdn.shopify.com/s/files/1/0659/0722/8923/products/2_d0323fb3-a3f3-4e3d-84cb-78ad9ecde19a.jpg?v=1680524003&width=360",
  },
  {
    _id: uuid(),
    title: "BLKTOP RIDER WASHED 'ASTRO RED/TEAM REGEL RED'",
    brand: "Sneakers",
    priceInMrp: 3999,
    discountInPercentage: 63,
    categoryName: "Puma",
    inStock: 15,
    featured: false,
    starRating: 3.2,
    cashOnDelivery: true,
    fastDelivery: false,
    imageSrc: "https://cdn.shopify.com/s/files/1/0659/0722/8923/files/2_580f81b8-e983-4919-95c4-bea15dfc6ebe.jpg?v=1700141992&width=360",
  },
  {
    _id: uuid(),
    title: "THE SMURFS SUEDE 'PUMAKIN PIE/BLACK",
    brand: "Sneakers",
    priceInMrp: 3999,
    discountInPercentage: 25,
    categoryName: "Puma",
    inStock: 20,
    featured: false,
    starRating: 4.4,
    cashOnDelivery: true,
    fastDelivery: false,
    imageSrc: "https://cdn.shopify.com/s/files/1/0659/0722/8923/files/2_502fb89a-cb76-4c1d-9515-44703d139636.jpg?v=1692254664&width=360",
  },
  {
    _id: uuid(),
    title: "AIR MAX 1 SE 'SUMMIT WHITE/SUMMIT WHITE-BLACK-WHITE'",
    brand: "Classic Sneakers",
    priceInMrp: 3000,
    discountInPercentage: 7,
    categoryName: "Nike",
    inStock: 10,
    featured: false,
    starRating: 4.0,
    cashOnDelivery: true,
    fastDelivery: false,
    imageSrc: "https://cdn.shopify.com/s/files/1/0659/0722/8923/files/FD9082-106-3.jpg?v=1704177156&width=360",
  },
];
