export {
    getFeaturedProducts,
    priceAfterDiscount,
    getUniqueValues,
    putCommasInPrice,
    getMaxPriceForFilter,
  getSortedProducts,
  getProductById,
  getFilteredProducts,
  totalItemsInCart,
  getTotalMrpInCart,
  getTotalAmount,
  getTotalDiscountOnMrp,
  getFinalAmountToPay,
  } from "./helpers";